### ISSUE TITLE
Не переводятся системные надписи

### ISSUE THREAD

**Issue by viktor-zin** [viktor-zin/afce#31]
Если в системе не установлены переводы Qt, то некоторые строчки остаются на английском. К примеру, если щелкнуть правой кнопкой мыши в окне с кодом, то выпадающее меню может оказаться на английском, если на компьютере не установлен Qt. Это может касаться как Linux, так и Windows.

Решение мне видится в следующем: нужно дополнительные файлы перевода копировать вместе  с дистрибутивом. В Linux — это `/usr/share/qt5/translations/qt_ru.qm`, в Windows —`C:\Qt\5.2.1\mingw48_32\translations\qt_ru.qm`. Либо нужно встроить эти файлы в файл ресурса. Думаю, как сделать универсальное решение. Нужно чтобы это из файл проект заводилось автоматически.

**Comment by glixx** [comment]
Увы, но практика показала, что при обновлении qt в репозитории получается, что перевода нет. Поэтому, надо не упаковывать эти переводы, а использовать системные.
То есть упакованные переводы оказываются старыми, и в них нет изменённых новых переводов, а как итог - отсутствие перевода.

**Comment by glixx** [comment]
Но есть ещё варианты: вообще убрать "О библиотеке Qt" из меню и/или сделать свою надпись. В этом случае у программы будет меньше зависимостей.
