### ISSUE TITLE
Улучшение кодогенерации для Python

### ISSUE THREAD

**Issue by Rb37** [viktor-zin/afce#50]
Предлагаю следующие улучшения.

**Точка с запятой**
После вызова функции и после присвоения не нужна точка с запятой.

**Отступ в 4 пробела**
Согласно PEP 8 Style Guide for Python Code - "Use 4 spaces per indentation level".
Для этого в файле py.json можно добавить "indentation_preference": "<4spaces>". 
Таким образом, можно сделать разный стиль отступов для разных языков и не нарушить обратную совместимость(если в json файле нет indentation_preference, то использовать умолчание).

**Оператор ветвления**
Python ругается если оставить пустую ветку else.
Либо не писать ветку else если в ней нет кода.
```
if x > 0:
    func()
x = 0
```
Либо писать pass.
```
if x > 0:
    func()
else:
    pass
x = 0
```
**Main**
Если делается простой скрипт то def main можно и не писать. Есть очевидный минус, если сделать import накого скрипта, то он выполнится вместо импортирования.
Если же писать def main то его надо потом вызвать.
```
def main():
    print("Good")
main()
```

Предлагаю обсудить.
Если владелец репозитория согласен с изменениями, то могу сделать pull requests.

**Comment by viktor-zin** [comment]
Предложения кажутся разумными. Давайте попробуем pull request.
